CREATE TABLE `peoplestrong-in-prod-cloud.etl_job_run.config_file5`
(
  cdc_table STRING,
  source_fp STRING,
  target_db STRING,
  target_fp STRING,
  bq_target_table STRING,
  pk STRING,
  region STRING,
  bq_projectid STRING,
  bq_target_dataset STRING,
  bq_partition_field STRING,
  bq_clustering_field STRING,
  epoc_cols STRING,
  epoc_nano_cols STRING,
  epoc_day_cols STRING,
  bit_to_int_col STRING,
  epoch_to_date_to_string_col STRING,
  non_epoch_datetime_col STRING,
  datetime_to_int_val_col STRING,
  datetime_null STRING,
  row_key_binary STRING,
  row_key_timestamp STRING,
  row_key_int STRING,
  row_key_bigint STRING,
  col_value_as_current_time_ist STRING,
  epoc_datetime_ist STRING,
  is_active INT64
);